language: generic
sudo: required
dist: trusty
install:
- sudo add-apt-repository -y "deb https://cran.cnr.berkeley.edu/bin/linux/ubuntu trusty/"
- sudo apt-get update
- sudo apt-get install -y --force-yes r-base r-base-dev
- sudo R -f install.R
script:
- ./init.sh
- ./report.sh
- ls -al diagrams
branches:
  only:
    - master
